name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  http: ^1.1.0
  equatable: ^2.0.5
  riverpod: ^2.3.6
  sizer: ^2.0.15
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  material_floating_search_bar: ^0.3.7
  connectivity_plus: ^4.0.1
  get: ^4.6.5
  dio: ^5.2.1+1
  lottie: ^2.4.0
  syncfusion_flutter_charts: ^22.1.37
  flutter_dotenv: ^5.1.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/